version: '3.8'

services:
  image_2_vector:
    build:
      context: ./src/vector_service
    ports:
      - "5000:5000"
    networks:
      - crochet-network

  llm_rag:
    build:
      context: ./src/rag_service
    ports:
      - "5001:5001"
    networks:
      - crochet-network

  test_runner:
    build:
      context: .
      dockerfile: test_runner/Dockerfile
    volumes:
      - ./integration_tests:/app/integration_tests
    working_dir: /app
    command: ["python", "-m", "pipenv", "run", "pytest", "integration_tests/test_integration.py"]
    networks:
      - crochet-network
    depends_on:
      - image_2_vector
      - llm_rag


networks:
  crochet-network:
    driver: bridge