name: CI on Push or Merge to Main

on:
  push:
    branches:
      - main  # Triggers when code is pushed to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9, 3.12] # We have both 3.9 and 3.12 required

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment (specifically Python 3.12)
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Step 2.1: Set PYTHONPATH to include the root directory (or src if relevant)
      # - name: Set PYTHONPATH
      #   run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV  # Adds current directory to PYTHONPATH


      # Step 3: Install dependencies - pylint, pytest and pytest-cov 
      - name: Install pytest and pytest-cov
        run: |
          python -m pip install --upgrade pip
          pip install pylint pytest pytest-cov
      
      # Step 4: Lint code with Pylint
       - name: Analysing the code with pylint
         run: |
           pylint $(git ls-files '*.py') || true  # Run linting, log output in GitHub Actions

      # Step 5: Run pytest with coverage and generate HTML report
      - name: Run tests with coverage
        run: |
          pytest --cov=. --cov-report=html

      # Step 6: Upload coverage report as an artifact
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: htmlcov  # The folder where pytest-cov stores HTML reports
    
     # Step 7: Upload test results
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results.xml