name: Continuous Integration and Continuous Deployment
run-name: ${{ github.actor }} submitted a CI CD Action for ML Tasks
on:
  push:
    branches: [ "main" ]

jobs:
  Explore-GitHub-Actions:
    if: contains(github.event.head_commit.message, '/run-')
    runs-on: ubuntu-latest
    steps:
      - run: echo "Comment ${{ github.event.head_commit.message }}"
      - run: echo "Job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "Job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "Branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - id: 'auth'
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'
      - name: Configure Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker # --quiet #authenticate to gcr
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Build Deployment Container 
        run: |-
          cd ${{ github.workspace }}/src/deployment/
          docker build -t crochet-app-deployment -f Dockerfile .
      - name: Run PDF Processor
        if: contains(github.event.head_commit.message, '/run-pdf-processor')
        run: |-
          docker run --rm --name crochet-app-deployment \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v ${{ github.workspace }}/src/frontend-react:/frontend-react \
            -v ${{ github.workspace }}/src/api-service:/api-service \
            -v ${{ github.workspace }}/src/pdf_processor:/pdf_processor \
            -v ${{ github.workspace }}/src/image_descriptions:/image_descriptions \
            --mount type=bind,source=$GOOGLE_APPLICATION_CREDENTIALS,target=/secrets/deployment.json \
            -e GOOGLE_APPLICATION_CREDENTIALS=/secrets/deployment.json \
            -e USE_GKE_GCLOUD_AUTH_PLUGIN=True \
            -e GCP_PROJECT=ac215-project \
            -e GCP_ZONE=us-central1-a \
            -e GCS_BUCKET_NAME=crochet-patterns-bucket-v2 \
            -e GCS_SERVICE_ACCOUNT=crochet-service@crochetai-new.iam.gserviceaccount.com \
            -e GCP_REGION=us-central1 \
            -e GCS_PACKAGE_URI=gs://crochet-app-trainer-code \
            crochet-app-deployment sh run-pdf-processor.sh
      - name: Run Image Descriptions
        if: contains(github.event.head_commit.message, '/run-image-descriptions')
        run: |-
          docker run --rm --name crochet-app-deployment \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v ${{ github.workspace }}/src/frontend-react:/frontend-react \
            -v ${{ github.workspace }}/src/api-service:/api-service \
            -v ${{ github.workspace }}/src/pdf_processor:/pdf_processor \
            -v ${{ github.workspace }}/src/image_descriptions:/image_descriptions \
            --mount type=bind,source=$GOOGLE_APPLICATION_CREDENTIALS,target=/secrets/deployment.json \
            -e GOOGLE_APPLICATION_CREDENTIALS=/secrets/deployment.json \
            -e USE_GKE_GCLOUD_AUTH_PLUGIN=True \
            -e GCP_PROJECT=ac215-project \
            -e GCP_ZONE=us-central1-a \
            -e GCS_BUCKET_NAME=crochet-patterns-bucket-v2 \
            -e GCS_SERVICE_ACCOUNT=crochet-service@crochetai-new.iam.gserviceaccount.com \
            -e GCP_REGION=us-central1 \
            -e GCS_PACKAGE_URI=gs://crochet-app-trainer-code \
            crochet-app-deployment sh run-image-descriptions.sh
      - name: Run ML Pipeline
        if: contains(github.event.head_commit.message, '/run-ml-pipeline')
        run: |-
          docker run --rm --name crochet-app-deployment \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v ${{ github.workspace }}/src/frontend-react:/frontend-react \
            -v ${{ github.workspace }}/src/api-service:/api-service \
            -v ${{ github.workspace }}/src/pdf_processor:/pdf_processor \
            -v ${{ github.workspace }}/src/image_descriptions:/image_descriptions \
            --mount type=bind,source=$GOOGLE_APPLICATION_CREDENTIALS,target=/secrets/deployment.json \
            -e GOOGLE_APPLICATION_CREDENTIALS=/secrets/deployment.json \
            -e USE_GKE_GCLOUD_AUTH_PLUGIN=True \
            -e GCP_PROJECT=ac215-project \
            -e GCP_ZONE=us-central1-a \
            -e GCS_BUCKET_NAME=crochet-patterns-bucket-v2 \
            -e GCS_SERVICE_ACCOUNT=crochet-service@crochetai-new.iam.gserviceaccount.com \
            -e GCP_REGION=us-central1 \
            -e GCS_PACKAGE_URI=gs://crochet-app-trainer-code \
            crochet-app-deployment sh run-ml-pipeline.sh
      - run: echo "Job's status is ${{ job.status }}."